# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Alexander Mohr
style_edition = "2024"
max_width = 100
newline_style = "Unix"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
unstable_features = true
