# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Alexander Mohr
line-length = 100

[lint]
select = [
    "E",      # pycodestyle (error)
    "F",      # pyflakes
    "B",      # bugbear
    "B9",
    "C4",     # flake8-comprehensions
    "SIM",    # flake8-simplify
    "I",      # isort
    "UP",     # pyupgrade
    "PIE",    # flake8-pie
    "PGH",    # pygrep-hooks
    "PYI",    # flake8-pyi
    "RUF",
    "PT",     # flake8-pytest-style
]
