// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Alexander Mohr

use shared::responses::{
    AgentResponse, AgentTagEntryResponse, ArchiveEntryResponse, ArchiveIndexStatusResponse,
    ArchiveInfoResponse, CalendarDayResponse, CalendarEventResponse, CreateAgentResponse,
    CreateApiTokenResponse, DashboardAgentLinkResponse, DashboardDestinationResponse,
    DashboardFindingResponse, DashboardOperationResponse, DashboardOverviewResponse,
    DashboardProtectionCoverageResponse, DashboardRepositoryCapacityResponse,
    DashboardSummaryCountersResponse, DashboardSummaryResponse, DashboardUpcomingScheduleResponse,
    DeleteApiTokenResponse, HealthCheckResponse, HealthResponse, InitRepoResponse,
    ListApiTokensResponse, LogEntryResponse, MeResponse, PassphraseResponse, PreferencesResponse,
    RefreshSessionResponse, RepoTagEntryResponse, RescanResponse, StorageRepoEntryResponse,
    StorageTrendByRepoEntryResponse, StorageTrendEntryResponse, TagResponse, TrendEntryResponse,
};
use utoipa::OpenApi;

use crate::{
    api::{
        agents::{CreateAgentRequest, UpdateAgentRequest},
        archives::{ContentEntry, ContentsResponse},
        auth::{ChangePasswordRequest, LoginRequest, LoginResponse, RefreshResponse},
        deploy::{DeployAgentRequest, DeployAgentResponse},
        dryrun::{DryRunFileEntry, DryRunRequest, DryRunResponse},
        excludes::SetGlobalExcludesRequest,
        logs::LogQuery,
        permissions::UpsertPermissionRequest,
        repos::{CreateRepoRequest, InitRepoRequest, UpdateRepoRequest},
        schedules::{CreateScheduleRequest, UpdateScheduleRequest},
        search::{SearchEntry, SearchResponse},
        system::{
            DatabaseStorageResponse, SettingsResponse, SshPublicKeyResponse, SystemResetResponse,
            UpdateSettingsRequest, VersionResponse,
        },
        tags::{CreateTagRequest, SetTagsRequest},
        tokens::CreateTokenRequest,
        users::{CreateUserRequest, UpdatePasswordRequest, UpdateRoleRequest},
    },
    db::{
        ActivityRow, AgentRow, ApiTokenRow, GlobalExcludesConfig, RepoPermissionRow, RepoRow,
        RepoWithStatsRow, ReportRow, ScheduleCountByAgent, ScheduleRow, ScheduleTargetRow,
        StorageStatRow, SystemEventRow, UserRow,
    },
    ssh::{
        DeployKeyRequest, DeployKeyResponse, DirEntryInfo, ListDirRequest, ListDirResponse,
        TestConnectionRequest, TestConnectionResponse,
    },
};

#[derive(OpenApi)]
#[openapi(
    info(title = "Assimilate API", version = "1.0.0"),
    paths(
        crate::api::auth::login,
        crate::api::auth::logout,
        crate::api::auth::me,
        crate::api::auth::refresh_session,
        crate::api::auth::change_password,
        crate::api::auth::get_preferences,
        crate::api::auth::update_preferences,
        crate::api::users::list_users,
        crate::api::users::create_user,
        crate::api::users::update_role,
        crate::api::users::update_password,
        crate::api::users::delete_user,
        crate::api::tokens::create_token,
        crate::api::tokens::list_tokens,
        crate::api::tokens::delete_token,
        crate::api::agents::list_agents,
        crate::api::agents::create_agent,
        crate::api::agents::get_agent,
        crate::api::agents::update_agent,
        crate::api::agents::delete_agent,
        crate::api::agents::regenerate_token,
        crate::api::agents::restart_agent,
        crate::api::repos::list_repos,
        crate::api::repos::get_agent_repos,
        crate::api::repos::create_repo,
        crate::api::repos::update_repo,
        crate::api::repos::delete_repo,
        crate::api::repos::get_passphrase,
        crate::api::repos::list_repos_with_stats,
        crate::api::repos::get_repo,
        crate::api::repos::init_repo,
        crate::api::repos::rescan_repo,
        crate::api::repos::sync_repo,
        crate::api::repos::reset_import,
        crate::api::repos::list_schedules_for_repo,
        crate::api::archives::list_archives,
        crate::api::archives::archive_info,
        crate::api::archives::delete_archive,
        crate::api::archives::list_contents,
        crate::api::archives::get_archive_index_status,
        crate::api::archives::extract_file,
        crate::api::dryrun::dry_run,
        crate::api::search::search_archive,
        crate::api::tags::list_archive_tags,
        crate::api::tags::add_archive_tag,
        crate::api::tags::remove_archive_tag,
        crate::api::deploy::deploy_agent,
        crate::api::deploy::fetch_service_unit,
        crate::api::schedules::list_schedules,
        crate::api::schedules::create_schedule,
        crate::api::schedules::get_schedule,
        crate::api::schedules::update_schedule,
        crate::api::schedules::delete_schedule,
        crate::api::schedules::run_schedule_now,
        crate::api::schedules::cancel_running_backup,
        crate::api::schedules::list_schedule_reports,
        crate::api::schedules::list_schedule_targets,
        crate::api::schedules::list_schedule_backup_sources,
        crate::api::excludes::get_excludes,
        crate::api::excludes::set_excludes,
        crate::api::permissions::list_for_repo,
        crate::api::permissions::upsert,
        crate::api::permissions::list_for_user,
        crate::api::tags::list_tags,
        crate::api::tags::create_tag,
        crate::api::tags::delete_tag,
        crate::api::tags::set_repo_tags,
        crate::api::tags::get_repo_tags,
        crate::api::tags::set_agent_tags,
        crate::api::tags::get_agent_tags,
        crate::api::tags::list_agent_tag_associations,
        crate::api::tags::list_repo_tag_associations,
        crate::api::stats::summary,
        crate::api::stats::dashboard_overview,
        crate::api::stats::storage,
        crate::api::stats::storage_breakdown,
        crate::api::stats::activity,
        crate::api::stats::system_events,
        crate::api::stats::health,
        crate::api::stats::trends,
        crate::api::stats::calendar,
        crate::api::stats::schedule_counts,
        crate::api::system::ssh_public_key,
        crate::api::system::ssh_regenerate_key,
        crate::api::system::get_settings,
        crate::api::system::update_settings,
        crate::api::system::get_database_storage,
        crate::api::system::get_version,
        crate::api::system::reset_system,
        crate::api::ssh::test_connection,
        crate::api::ssh::deploy_key,
        crate::api::ssh::list_dir,
        crate::api::health::health,
        crate::api::reports::list_reports,
        crate::api::logs::get_logs,
        crate::api::keys::export_key,
        crate::api::keys::import_key,
        crate::api::keys::change_passphrase,
        crate::api::restore::download_files,
        crate::api::restore::restore_files,
    ),
    components(schemas(
        LoginRequest,
        LoginResponse,
        MeResponse,
        RefreshResponse,
        ChangePasswordRequest,
        CreateUserRequest,
        UpdateRoleRequest,
        UpdatePasswordRequest,
        CreateTokenRequest,
        CreateApiTokenResponse,
        ListApiTokensResponse,
        UserRow,
        ApiTokenRow,
        AgentRow,
        AgentResponse,
        CreateAgentRequest,
        CreateAgentResponse,
        UpdateAgentRequest,
        RepoRow,
        RepoWithStatsRow,
        CreateRepoRequest,
        UpdateRepoRequest,
        PassphraseResponse,
        InitRepoRequest,
        InitRepoResponse,
        RescanResponse,
        ArchiveEntryResponse,
        ArchiveInfoResponse,
        ArchiveIndexStatusResponse,
        ContentEntry,
        ContentsResponse,
        DeployAgentRequest,
        DeployAgentResponse,
        CreateScheduleRequest,
        UpdateScheduleRequest,
        ScheduleRow,
        ScheduleTargetRow,
        DryRunRequest,
        DryRunFileEntry,
        DryRunResponse,
        SetGlobalExcludesRequest,
        GlobalExcludesConfig,
        UpsertPermissionRequest,
        RepoPermissionRow,
        CreateTagRequest,
        SetTagsRequest,
        TagResponse,
        AgentTagEntryResponse,
        RepoTagEntryResponse,
        DashboardSummaryResponse,
        DashboardOverviewResponse,
        DashboardSummaryCountersResponse,
        DashboardFindingResponse,
        DashboardDestinationResponse,
        DashboardProtectionCoverageResponse,
        DashboardAgentLinkResponse,
        DashboardOperationResponse,
        DashboardUpcomingScheduleResponse,
        DashboardRepositoryCapacityResponse,
        StorageRepoEntryResponse,
        HealthResponse,
        TrendEntryResponse,
        StorageTrendEntryResponse,
        StorageTrendByRepoEntryResponse,
        CalendarDayResponse,
        CalendarEventResponse,
        crate::api::stats::TrendsQuery,
        crate::api::stats::CalendarQuery,
        StorageStatRow,
        ScheduleCountByAgent,
        ActivityRow,
        SystemEventRow,
        SshPublicKeyResponse,
        SettingsResponse,
        UpdateSettingsRequest,
        DatabaseStorageResponse,
        crate::db::DatabaseRelationSizeRow,
        VersionResponse,
        SystemResetResponse,
        TestConnectionRequest,
        TestConnectionResponse,
        DeployKeyRequest,
        DeployKeyResponse,
        ListDirRequest,
        ListDirResponse,
        DirEntryInfo,
        ReportRow,
        LogQuery,
        SearchEntry,
        SearchResponse,
        LogEntryResponse,
        crate::api::keys::ImportKeyRequest,
        crate::api::keys::ChangePassphraseRequest,
        crate::api::restore::DownloadFilesRequest,
        crate::api::restore::RestoreFilesRequest,
        crate::api::restore::RestoreFilesResponse,
        HealthCheckResponse,
        DeleteApiTokenResponse,
        RefreshSessionResponse,
        PreferencesResponse,
    ))
)]
pub struct ApiDoc;
