# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Alexander Mohr
name: Pre-commit

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Run checks
        uses: eclipse-opensovd/cicd-workflows/pre-commit-action@f43fba4e91b39a92b0948633fbbdc080ef4bb3d3
        with:
          rust-toolchain: "nightly"
          config-path: .pre-commit-config.yaml
